version: "3"

services:
  frontend:
    build: ./frontend/
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/.env
    # network 설정에 따라 삭제 가능
    expose:
      - "8080"
    healthcheck:
      interval: 5s
      test: ["CMD-SHELL", "curl -k https://localhost:8080 || exit 1"]
      timeout: 3s
      retries: 3
    image: frontend:LastExTranscendence
    init: true
    networks:
      - transcendence
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - frontend:/app

  backend:
    build: ./backend/
    container_name: frontend
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    # network 설정에 따라 삭제 가능
    expose:
      - "3000"
    healthcheck:
      interval: 5s
      test: ["CMD-SHELL", "curl -k https://localhost:3000 || exit 1"]
      timeout: 3s
      retries: 3
    image: backend:LastExTranscendence
    init: true
    networks:
      - transcendence
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - backend:/app

  postgresql:
    container_name: postgresql
    env_file:
      - ./postgresql.env
    # network 설정에 따라 삭제 가능
    expose:
      - "5432"
    healthcheck:
      interval: 5s
      test: ["CMD-SHELL", "pg_isready -d db_local || exit 1"]
      timeout: 3s
      retries: 3
    image: postgres:16-alpine3.18
    networks:
      - transcendence
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf

  # pgadmin:

networks:
  transcendence:
    name: transcendence

volumes:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ./frontend

  backend:
    name: backend
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ./backend

  postgresql:
    name: postgresql
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ./data
